CIRCUITPY_WIFI_SSID=""
CIRCUITPY_WIFI_PASSWORD=""
CIRCUITPY_WEB_API_PASSWORD=""
CIRCUITPY_WEB_API_PORT=8080

IP_ADDRESS="192.168.1.234"
NETMASK="255.255.255.0"
GATEWAY="192.168.1.1"
NTP_ADDRESS="pool.ntp.org"